In [8]:
import numpy as np
from scipy import linalg as LA

In [9]:
def message_formatter(message):
    if len(message) % 2 != 0:
        message = message + ' '
    return [message[i:i+2] for i in range(0, len(message), 2)]

def simple_encrypt(message, key):
    message = [ord(c) for c in list(message)]
    convert = ""
    testd = key.dot(message)

    for i in range(0, len(testd)):
        convert = convert + chr(testd[i])
    return convert
    
def simple_decrypt(message, key):
    testd = [ord(c) for c in list(message)]
    keyinv = LA.inv(key)
    converted = keyinv.dot(testd)
    output = ''
    for i in range(0, len(converted)):
        z = int(round(converted[i]))
        output = output + chr(z)
    return output

def encryptor(message, key):
    return ''.join([simple_encrypt(chunk, key) for chunk in message_formatter(message)])
    
def decryptor(message, key):
    return ''.join([simple_decrypt(chunk, key) for chunk in message_formatter(message)])

In [13]:
m = "Hello!"
print(m)

m_ascii = [ord(c) for c in m]
print(m_ascii)

Hello!
[72, 101, 108, 108, 111, 33]


In [12]:
k = np.array([[3,9],[5,8]])
print(k)

[[3 9]
 [5 8]]


In [25]:
encryptor("Hello!", np.array([[1,2],[3,4]]))

'Ēɬń˴±Ǒ'

In [28]:
m_ascii[4:6]

[111, 33]

In [29]:
np.array(m_ascii[4:6]).dot(k)

array([ 498, 1263])

In [18]:
encryptor('Please join my meeting from your computer, tablet or smartphone.', k)

'ҼӰҘԁӦէКϰӾճɪ̦\u0588שеЈҼԡԍ\u058cө՞϶ϐԽֲɧ̡ՒוաיϛθԢ֓խטөլˢΚѴрҕӵӑՄɼ̈́ՏֻѫиҰԩժךӸհԫ֛ˍͩ'

In [12]:
decryptor('ҼӰҘԁӦէКϰӾճɪ̦\u0588שеЈҼԡԍ\u058cө՞϶ϐԽֲɧ̡ՒוաיϛθԢ֓խטөլˢΚѴрҕӵӑՄɼ̈́ՏֻѫиҰԩժךӸհԫ֛ˍͩ', k)

'Please join my meeting from your computer, tablet or smartphone.'

In [3]:
## result = ''
message = ''
choice = ''
 
while choice != '-1':
    choice = input("\nDo you want to encrypt or decrypt the message?\nEnter 1 to Encrypt, 2 to Decrypt, -1 to Exit Program: ")
 
    if choice == '1':
        message = input("\nEnter the message to encrypt: ")
        key_input = input("\nPlease enter a 2x2 matrix as your encryption key: ")
        
        key = [int(i) for i in key_input.split(',')]
        key_matrix = np.array([key[i:i+2] for i in range(0, len(key), 2)])
        
        print(encryptor(message, key_matrix))
 
    elif choice == '2':
        message = input("\nEnter the message to decrypt: ")
        key_input2 = input("\nPlease enter a 2x2 matrix as your encryption key: ")
        
        key2 = [int(i) for i in key_input2.split(',')]
        key_matrix2 = np.array([key2[i:i+2] for i in range(0, len(key2), 2)])
        
        print(decryptor(message, key_matrix2))
 
    elif choice != '-1':
        print ("You have entered an invalid choice. Please try again.\n\n")


Do you want to encrypt or decrypt the message?
Enter 1 to Encrypt, 2 to Decrypt, -1 to Exit Program: 1

Enter the message to encrypt: the rain in Spain

Please enter a 2x2 matrix as your encryption key: 2,4,6,8
ʈ׸Ŋ͞ɨִʊצǤЈŜΔɦղɦ֎ŜΔ

Do you want to encrypt or decrypt the message?
Enter 1 to Encrypt, 2 to Decrypt, -1 to Exit Program: 2

Enter the message to decrypt: ʈ׸Ŋ͞ɨִʊצǤЈŜΔɦղɦ֎ŜΔ

Please enter a 2x2 matrix as your encryption key: 2,4,6,8
the rain in Spain 

Do you want to encrypt or decrypt the message?
Enter 1 to Encrypt, 2 to Decrypt, -1 to Exit Program: ʈ׸Ŋ͞ɨִʊצǤЈŜΔɦղɦ֎ŜΔ
You have entered an invalid choice. Please try again.



Do you want to encrypt or decrypt the message?
Enter 1 to Encrypt, 2 to Decrypt, -1 to Exit Program: 2

Enter the message to decrypt: ʈ׸Ŋ͞ɨִʊצǤЈŜΔɦղɦ֎ŜΔ

Please enter a 2x2 matrix as your encryption key: 1,3,5,7


ValueError: chr() arg not in range(0x110000)

In [5]:
m = message_formatter('the rain in Spain')
print(m)

['th', 'e ', 'ra', 'in', ' i', 'n ', 'Sp', 'ai', 'n ']


In [6]:
m

['th', 'e ', 'ra', 'in', ' i', 'n ', 'Sp', 'ai', 'n ']

In [16]:
m[0][0]

't'

In [17]:
ord('t')

116

In [18]:
chr(116)

't'

In [20]:
a = [ord(c) for c in 'th']
a

[116, 104]

In [22]:
key = np.array([[2, 4], [6, 8]])

In [23]:
key

array([[2, 4],
       [6, 8]])

In [26]:
b = key.dot(a)
b

array([ 648, 1528])

In [28]:
[print(chr(c)) for c in b]

ʈ
׸


[None, None]