In [1]:
import numpy as np
from scipy import linalg as LA

### Question 1: Part I

In [2]:
A=np.array([[1,2,3]
            ,[1,1,1]
            ,[1,3,6]])

b=np.array([7,5,11])

In [3]:
P, L, U = LA.lu(A)

In [4]:
print('Matrix P: \n {} \n'.format(P))

print('Matrix L: \n {} \n'.format(L))

print('Matrix U: \n {} \n'.format(U))

Matrix P: 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Matrix L: 
 [[ 1.  0.  0.]
 [ 1.  1.  0.]
 [ 1. -1.  1.]] 

Matrix U: 
 [[ 1.  2.  3.]
 [ 0. -1. -2.]
 [ 0.  0.  1.]] 



### Question 1: Part II

In [5]:
LA.solve(A, b)

array([ 5., -2.,  2.])

### Question 2: Part II

In [6]:
A2=np.array([[1,1,1]
            ,[1,2,2]
            ,[1,2,3]])


In [7]:
LA.inv(A2)

array([[ 2., -1., -0.],
       [-1.,  2., -1.],
       [ 0., -1.,  1.]])