In [1]:
import numpy as np
from scipy import linalg as LA

## Question 1

In [2]:
A = np.array([[1,1,2],
              [0,0,1],
              [1,0,0]])

In [3]:
A

array([[1, 1, 2],
       [0, 0, 1],
       [1, 0, 0]])

In [4]:
Q, R = np.linalg.qr(A)
print('Matrix Q: \n {} \n'.format(Q))

Matrix Q: 
 [[-0.70710678 -0.70710678  0.        ]
 [-0.          0.          1.        ]
 [-0.70710678  0.70710678  0.        ]] 



In [5]:
1/(2**.5)

0.7071067811865475

## Question 2

In [6]:
A = np.array([[1,0,1],[0,1,1]]).T
b = np.array([1,1,0])

print(A)
print("")
print(b)

[[1 0]
 [0 1]
 [1 1]]

[1 1 0]


In [7]:
A_inv = LA.inv(A.T.dot(A))
AtB = A.T.dot(b)

In [8]:
A.T.dot(b)

array([1, 1])

In [9]:
A_inv.dot(AtB)

array([0.33333333, 0.33333333])

In [10]:
X, resid, r, s = LA.lstsq(A, b)
X

array([0.33333333, 0.33333333])