In [1]:
import numpy as np
from scipy import linalg as LA

In [4]:
A = np.array([[4,-3],[2,-1]])

In [17]:
values, vectors = LA.eig(A)

### Eigenvalues

In [24]:
values

array([2.+0.j, 1.+0.j])

The eigenvalues found here match the eigevalues that I found by hand.

### Eigenvectors

In [25]:
vectors

array([[0.83205029, 0.70710678],
       [0.5547002 , 0.70710678]])

In [26]:
3/(13**(1/2))

0.8320502943378437

In [27]:
2/(13**(1/2))

0.5547001962252291

In [28]:
1/(2**(1/2))

0.7071067811865475

The eigvenvectors match the ones I found by hand. The first column is my x2 and the second columns is my x1. I realize now I probably should have put them in descending order but I liked the symmetry of lambda1=1, lambda2=2

In [29]:
LA.inv(vectors)

array([[ 3.60555128, -3.60555128],
       [-2.82842712,  4.24264069]])