In [1]:
import numpy as np
from scipy import linalg as LA


# Define matrices
A=np.array([
            [1,2,3]
            ,[2,2,4]
            ,[0,-1,0]
           ]) ## 3X3

B=np.array([[1,2,3],
            [1,2,3],
            [1,2,3]
           ]) ## 3X3

b=np.array([1,2,3])

c=np.array([2,1,0])

print('Matrix A: \n {} \n'.format(A))
print('Matrix B: \n {} \n'.format(B))
print('Vector b: \n {} '.format(b))
print('Vector c: \n {} '.format(c))

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix B: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

Vector b: 
 [1 2 3] 
Vector c: 
 [2 1 0] 


# Matrix Inverse

In [4]:
Ainv = LA.inv(A)
print('Matrix A: \n {} \n'.format(A))
print('Inverse of Matrix A: \n {} \n'.format(Ainv))


print('Test A dot Ainv:  \n {} \n'.format(A.dot(Ainv)))
print('Test Ainv dot A:  \n {} \n'.format(Ainv.dot(A)))


Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Inverse of Matrix A: 
 [[-2.   1.5 -1. ]
 [ 0.   0.  -1. ]
 [ 1.  -0.5  1. ]] 

Test A dot Ainv:  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 

Test Ainv dot A:  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 



In [5]:
## What is wrong?

print('Matrix B: \n {} \n'.format(B))
Binv = LA.inv(B)

Matrix B: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 



LinAlgError: singular matrix

# Determinant

In [6]:
DetA=LA.det(A)

print('Matrix A: \n {} \n'.format(A))
print('Det(A): \n {} \n'.format(DetA))

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Det(A): 
 -2.0 



In [7]:
DetB=LA.det(B)
print('Matrix B: \n {} \n'.format(B))
print('Det(B): \n {} \n'.format(DetB))

Matrix B: 
 [[1 2 3]
 [1 2 3]
 [1 2 3]] 

Det(B): 
 0.0 



# LU Decompostion of a Matrix

In [8]:
print('Matrix A: \n {} \n'.format(A))

P, L, U = LA.lu(A)
print("This is a LU factorization routine written for Scipy \n")

print('Matrix P: \n {} \n'.format(P))

print('Matrix L: \n {} \n'.format(L))

print('Matrix U: \n {} \n'.format(U))

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

This is a LU factorization routine written for Scipy 

Matrix P: 
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] 

Matrix L: 
 [[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.  -1.   1. ]] 

Matrix U: 
 [[2. 2. 4.]
 [0. 1. 1.]
 [0. 0. 1.]] 



In [9]:
print("Perform the multiplication P*L \n")

print('Matrix A: \n {} \n'.format(A))

PL, U = LA.lu(A,permute_l = True)

print('Matrix PL: \n {} \n'.format(PL))

print('Matrix U: \n {} \n'.format(U))

Perform the multiplication P*L 

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix PL: 
 [[ 0.5  1.   0. ]
 [ 1.   0.   0. ]
 [ 0.  -1.   1. ]] 

Matrix U: 
 [[2. 2. 4.]
 [0. 1. 1.]
 [0. 0. 1.]] 



In [10]:
print("Based on LAPACK \n")

print('Matrix A: \n {} \n'.format(A))

lu, piv = LA.lu_factor(A)

#Matrix containing U in its upper triangle, and L in its lower triangle.
print('Matrix lu: \n {} \n'.format(lu)) 

# Pivot indices representing the permutation matrix P: row i of matrix was interchanged with row piv[i].
print('Pivots: \n {} \n'.format(piv)) 

Based on LAPACK 

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix lu: 
 [[ 2.   2.   4. ]
 [ 0.5  1.   1. ]
 [ 0.  -1.   1. ]] 

Pivots: 
 [1 1 2] 



# Solve linear system of equations , A x = b, using the LU factorization

In [11]:
print('Matrix A: \n {} \n'.format(A))
print('Matrix b: \n {} \n'.format(b))


Ainv = LA.inv(A)
print('Inverse of Matrix A: \n {} \n'.format(Ainv))

print("x=Ainv * b: (Correct)")
x= Ainv.dot(b)
print(x)
print("Test A*x ?=b : (Correct)")
print(A.dot(x))
print('\n')

print("x=b*Ainv: (Incorrect)")
x= b.dot(Ainv)
print(x)
print("Test A*x ?=b : (Incorrect)")
print(A.dot(x))

Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix b: 
 [1 2 3] 

Inverse of Matrix A: 
 [[-2.   1.5 -1. ]
 [ 0.   0.  -1. ]
 [ 1.  -0.5  1. ]] 

x=Ainv * b: (Correct)
[-2. -3.  3.]
Test A*x ?=b : (Correct)
[1. 2. 3.]


x=b*Ainv: (Incorrect)
[1. 0. 0.]
Test A*x ?=b : (Incorrect)
[1. 2. 0.]


In [12]:
print('Matrix A: \n {} \n'.format(A))
print('Matrix b: \n {} \n'.format(b))
print('Matrix c: \n {} \n'.format(c))

x_b = LA.lu_solve((lu,piv), b) # Factorization of the coefficient matrix A, as given by lu_factor
x_c = LA.lu_solve((lu,piv), c) # Factorization of the coefficient matrix A, as given by lu_factor

print("x for b ( Using lu_solve() ): \n {} \n".format(x_b))
print("x for c ( Using lu_solve() ): \n {} \n".format(x_c))

x = LA.solve(A,b) # Solve the equation Ax = b for x.

print("x ( Using solve() ): \n {} \n".format(x))


Matrix A: 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix b: 
 [1 2 3] 

Matrix c: 
 [2 1 0] 

x for b ( Using lu_solve() ): 
 [-2. -3.  3.] 

x for c ( Using lu_solve() ): 
 [-2.5  0.   1.5] 

x ( Using solve() ): 
 [-2. -3.  3.] 

