In [1]:
import numpy as np
from scipy import linalg as LA


# Define matrices 

# Matrix A:
#
# [1 2 3
# 2 2 4
# 0 -1 0]
A=np.array([    [1,2,3],[2,2,4],[0,-1,0]     ]) ## 3X3


B=np.array([[-2.0,3,2],[0,1,5],[9,6,11]]) ## 3X3
C=np.array([[2,-2],[4,-3]]) ## 2X2
D=np.array([[1,-3],[1,2], [5,5]]) ## 3X2


# Define vectors
v=np.array([4,-2,3]) ## 3x1

print('Matrix A = \n',A)
print('Shape of Matrix A :', A.shape)
print('Size of Matrix A :', A.size)
print('\n')

print('Vector v = ',v)
print('Shape of Vector v :', v.shape)
print('Size of Vector v :', v.size)



Matrix A = 
 [[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]]
Shape of Matrix A : (3, 3)
Size of Matrix A : 9


Vector v =  [ 4 -2  3]
Shape of Vector v : (3,)
Size of Vector v : 3


# Matrix Addition/Subtraction


In [2]:
print('Matrix A:')
print(A,'\n')
print('Matrix B:')
print(B,'\n')

print('A+B :')
print(A+B,'\n')

print('B-A :')
print(B-A,'\n')


Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix B:
[[-2.  3.  2.]
 [ 0.  1.  5.]
 [ 9.  6. 11.]] 

A+B :
[[-1.  5.  5.]
 [ 2.  3.  9.]
 [ 9.  5. 11.]] 

B-A :
[[-3.  1. -1.]
 [-2. -1.  1.]
 [ 9.  7. 11.]] 



In [3]:
print('Matrix B:')
print(B,'\n')
print('Matrix C:')
print(C,'\n')

### What is wrong here?
B+C

Matrix B:
[[-2.  3.  2.]
 [ 0.  1.  5.]
 [ 9.  6. 11.]] 

Matrix C:
[[ 2 -2]
 [ 4 -3]] 



ValueError: operands could not be broadcast together with shapes (3,3) (2,2) 

# Matrix Multiplication

In [4]:
print('Matrix A:')
print(A,'\n')
print('Matrix B:')
print(B,'\n')


print('A dot B :') #matrix multiplication
print(A.dot(B),'\n')

print('A * B :') #not matrix multiplication!
print(A*B,'\n')

Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix B:
[[-2.  3.  2.]
 [ 0.  1.  5.]
 [ 9.  6. 11.]] 

A dot B :
[[25. 23. 45.]
 [32. 32. 58.]
 [ 0. -1. -5.]] 

A * B :
[[-2.  6.  6.]
 [ 0.  2. 20.]
 [ 0. -6.  0.]] 



In [5]:
print('Matrix A:')
print(A,'\n')
print('Matrix D:')
print(D,'\n')


print('A dot D :') #matrix multiplication
print(A.dot(D),'\n')



Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix D:
[[ 1 -3]
 [ 1  2]
 [ 5  5]] 

A dot D :
[[18 16]
 [24 18]
 [-1 -2]] 



In [6]:
print('Matrix A:')
print(A,'\n')
print('Matrix C:')
print(C,'\n')
print('Matrix A - Shape:')
print(A.shape,'\n')
print('Matrix C - Shape:')
print(C.shape,'\n')

#### What is wrong here?

print('A dot C :') # matrix multiplication
print(A.dot(C))

Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Matrix C:
[[ 2 -2]
 [ 4 -3]] 

Matrix A - Shape:
(3, 3) 

Matrix C - Shape:
(2, 2) 

A dot C :


ValueError: shapes (3,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

# Vector Multiplication

In [7]:
print('Matrix A:')
print(A,'\n')
print('Vector v:')
print(v,'\n')


y=A.dot(v) #matrix - vector multiplication
print('y = A dot v :')
print(y,'\n')

print('Shape of y :')
print(y.shape,'\n')


print('A*v :')
print(A*v) #not matrix - vector multiplication!

Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Vector v:
[ 4 -2  3] 

y = A dot v :
[ 9 16  2] 

Shape of y :
(3,) 

A*v :
[[ 4 -4  9]
 [ 8 -4 12]
 [ 0  2  0]]


In [8]:
print('Matrix A:')
print(A,'\n')

diag = A.diagonal() ## or A.diag
print('Diagnonal vector of matrix A :', diag)
print('Shape of the diagnonal vector :', diag.shape,'\n')


print('Transpose of Matrix A :')
print(A.transpose())
print(A.T,'\n')


print('trace of Matrix A :',A.trace(),'\n')


I = np.eye(4)

print('Identity matrix:')
print( I,'\n')




#print('Matrix A Type :', A.dtype)
#print('Matrix B Type :', B.dtype,'\n')
#np.zeros((3,4))
#np.zeros_like((3,4))

Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Diagnonal vector of matrix A : [1 2 0]
Shape of the diagnonal vector : (3,) 

Transpose of Matrix A :
[[ 1  2  0]
 [ 2  2 -1]
 [ 3  4  0]]
[[ 1  2  0]
 [ 2  2 -1]
 [ 3  4  0]] 

trace of Matrix A : 3 

Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 



In [9]:
#print('Matrix A:')
#print(A,'\n')


#print('Matrix A 1-norm:')
#print('Definition: max(sum(abs(A), axis=0))')
#print('Max(3,5,7)')
#print(LA.norm(A,1),'\n')



#print('Matrix A Inf norm:')
#print('Definition: max(sum(abs(A), axis=1))')
#print('Max(6,8,1)')
#print(LA.norm(A,np.inf))

# Triangular Matrices

In [11]:
print('Matrix A:')
print(A,'\n')

L = LA.tril(A)
U = LA.triu(A)

print('Lower Triangular Matrix:')
print(L,'\n')

print('Upper Triangular Matrix:')
print(U,'\n')

Matrix A:
[[ 1  2  3]
 [ 2  2  4]
 [ 0 -1  0]] 

Lower Triangular Matrix:
[[ 1  0  0]
 [ 2  2  0]
 [ 0 -1  0]] 

Upper Triangular Matrix:
[[1 2 3]
 [0 2 4]
 [0 0 0]] 

